ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources  :cats 
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'date'
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: { in: %w(white black brown orange gray blue)}
    validates :sex, inclusion: { in: %w(M F)}

    def age
        Date.today.year - self.birth_date.year
    end
end

ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: { in: %w(PENDING APPROVED DENIED)}

    belongs_to :cat, dependent: :destroy,
      primary_key: :id,
      foreign_key: :cat_id,
      class_name: :Cat
    
    def overlapping_requests 
        
    end 
    
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all 
    end

    def show
        @cat = Cat.find(params[:id])
    end 

    def new
        @cat = Cat.new 
    end

    def create
        cat = Cat.new(cat_params)
        if cat.save
            redirect_to cat_url(cat)
        else
            render :new 
        end 
    end

    def edit
        @cat = Cat.find(params[:id])
    end

    def update
        cat = Cat.find(params[:id])
        if cat.update(cat_params)
            redirect_to cat_url(cat)
        else
            render :edit 
        end
    end

    private 

    def cat_params
        params.require(:cat).permit(:name, :color, :sex, :birth_date, :description)
    end 
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/_form.html.erb
<% if type == :edit %>
<% action_url = cat_url(cat) %>
<% elsif type == :new %>
<% action_url = cats_url%>
<% end %>

<form action="<%= action_url %>" method="post">
    <% if type == :edit %>
    <input type="hidden" name="_method" value="PATCH">
    <% end %>
    <label for="name">Name: </label>
    <input type='text' id='name' name="cat[name]" value="<%=cat.name%>">
    <br>
    <label for="color">Color: </label>
    <select id='color' name="cat[color]" value="<%=cat.color%>">
        <option value='black'>black</option>
        <option value='white'>white</option>
        <option value='brown'>brown</option>
        <option value='gray'>gray</option>
        <option value='blue'>blue</option>
        <option value='orange'>orange</option>
    </select>
    <br>
    <label for="birth_date">Birth_date: </label>
    <input type='date' id='birth_date' name="cat[birth_date]" value="<%=cat.birth_date%>">
    <br>
    <label for="sex">Sex: </label>
    <select id='sex' name="cat[sex]" value="<%=cat.sex%>">
        <option value='M'>M</option>
        <option value='F'>F</option>
    </select>
    <br><br>
    <label for="description">Description: </label>
    <textarea id='description' name="cat[description]"><%=cat.description%></textarea>
    <br>
    <input type='submit' value="<%= (type == :edit) ? 'Edit cat' : 'Add cat'%>">


</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<h2> Edit cat </h2>
<%= render 'form', cat: @cat, type: :edit%>
<a href="<%= cat_url(@cat) %>"> Back to cat! </a>

ninety_nine_cats/app/views/cats/index.html.erb
<h2>All Cats</h2>

<ul>
    <% @cats.each do |cat| %>
    <li>Name: <%= cat.name %> </li>
    <a href="<%= cat_url(cat) %>"> Show me the cat! </a>    
    <br><br>
    <% end %>
    <a href="<%= new_cat_url %>"> Create a cat! </a>
</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<h2> Create a cat </h2>
<%= render 'form', cat: @cat, type: :new %>
<a href="<%= cats_url %>">See all cats </a>

ninety_nine_cats/app/views/cats/show.html.erb
    
<table>
    <thead>
        <tr>
            <th colspan="2"> Meet a cat </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Name: </td>
            <td><%= @cat.name %></td>
        </tr>
        <tr>
            <td>Color: </td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex: </td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Birth_date: </td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Age: </td>
            <td>About <%= @cat.age %> years </td>
        </tr>
        <tr>
            <td>Description: </td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>

<a href="<%= edit_cat_url %>"> Edit the cat! </a>
<br>
<a href="<%= cats_url %>">See all cats </a>
  
    

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>